name: bootstrap_example
description: Demonstrates how to use the bootstrap plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  font_awesome_flutter: ^10.2.1
  responsive_grid: ^2.1.0
  get_bootstrap:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/