name: bootstrap_example
description: Demonstrates how to use the bootstrap plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  file_picker: ^5.2.3
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  get_bootstrap:
    path: ../
  url_launcher: ^6.1.7
  google_fonts: ^3.0.1

dev_dependencies:
  dart_code_metrics: ^5.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - fonts/
