name: bootstrap_example
description: Demonstrates how to use the bootstrap plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  get_bootstrap:
    path: ../
  url_launcher: ^6.1.8

dev_dependencies:
  dart_code_metrics: ^5.5.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans/OpenSans-Light.ttf
          weight: 100
        - asset: fonts/OpenSans/OpenSans-Light.ttf
          weight: 200
        - asset: fonts/OpenSans/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans/OpenSans-LightItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/OpenSans/OpenSans-LightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/OpenSans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic

        - asset: fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans/OpenSans-Italic.ttf
          weight: 400
          style: italic

        - asset: fonts/OpenSans/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/OpenSans/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: fonts/OpenSans/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans/OpenSans-BoldItalic.ttf
          weight: 700
        
        - asset: fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
        - asset: fonts/OpenSans/OpenSans-ExtraBold.ttf
          weight: 900
        - asset: fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf
          weight: 900
       
    - family: CourierPrime
      fonts:
        - asset: fonts/CourierPrime/CourierPrime-Regular.ttf
        - asset: fonts/CourierPrime/CourierPrime-Italic.ttf
          style: italic
        - asset: fonts/CourierPrime/CourierPrime-Bold.ttf
          weight: 700
        - asset: fonts/CourierPrime/CourierPrime-BoldItalic.ttf
          weight: 700
          style: italic