name: get_bootstrap
description: Este projeto foi desenvolvido com base a documentação do Bootstrap,
  porém foi desenvolvido a mão para uso no Flutter.
version: 0.5.0
homepage: https://github.com/vitoramaral10/get_bootstrap

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: '>=2.5.0'

dependencies:

  flutter:
    sdk: flutter
  google_fonts: ^3.0.1

dev_dependencies:
  dart_code_metrics: ^5.0.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
